<?
/*
echo "<p class=\"copyright\">\n";
echo "<a href=\"http://jigsaw.w3.org/css-validator/validator?uri=";
echo "http://$HostName$ThisScript\">";
echo "<img align=\"top\" style=\"border:0;width:88px;height:31px\"";
echo " src=\"http://jigsaw.w3.org/css-validator/images/vcss\""; 
echo " alt=\"Valid CSS!\">";
echo "</a>\n";

echo "<a href=\"http://validator.w3.org/check?uri=";
echo "http://$HostName$ThisScript\">";
echo "<img align=\"top\" style=\"border:0;width:88px;height:31px\"";
echo " src=\"http://www.w3.org/Icons/valid-html401\""; 
echo " alt=\"Valid HTML 4.01!\">";
echo "</a>\n";
*/

echo "\n\n<div class=\"footer\">";
echo "Generated by\n   <em>";
echo "<a href=\"" . $app["url"] . "\">";
echo $app["name"];
echo "</a>";
echo " ver. " . $app["version"];
echo "</em>\n";
echo "</div>\n";
?>
